### ISSUE TITLE
Failure Flashing the FW Data/Config File

### ISSUE THREAD

**Issue by Darklegion1978** [Solaris17/ARC-Firmware-Tool#13]
The following Issue,.... the File is correct, but the Flash Utility wont flash and says its not correct.

Any suggestions for this failure?

Greetings

Flashing FW Data File:
 "C:\VGA_Acer_31.0.101.4824_W10x64W11x64_A\Graphics\fwdata\dg2_acer_predator-bifrost-a770_config-data.bin"

Error: firmware data version is not compatible with the installed one (OEM version)
Image:  Fw Data Version: Major Version: 101, OEM Manufacturing Data Version: 2, Major VCN: 1
Device: Fw Data Version: Major Version: 101, OEM Manufacturing Data Version: 2, Major VCN: 1

Flashing complete!

**Comment by Solaris17** [comment]
Hello.

this is not a failure. As indicated by the log the file is exactly the same. Intel does not allow the downgrade of config data.
