### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by jbagg** [Solaris17/ARC-Firmware-Tool#31]
Hello, the linux build will not run on Debian 12 (currently stable), as it wants a newer glibc.  Debian 12 ships with 2.36

> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by libigsc.so.0)

I installed the [dotnet sdk](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian)

> sudo apt-get install dotnet-sdk-9.0

and then tried to built it....

dotnet build ARC\ Firmware\ Tool.csproj --runtime linux-x64

but dotnet keeps trying to cross compile it for windows...

> /usr/share/dotnet/sdk/9.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true.

**Comment by Solaris17** [comment]
I may at some point built for debian stable, but it is difficult to build for every least common denominator. 

If you need a build for your specific OS that runs behind release versions you can build it with the instructions from upstream.

https://github.com/intel/igsc
