### ISSUE TITLE
Fan curve

### ISSUE THREAD

**Issue by MrJosu** [Solaris17/ARC-Firmware-Tool#32]
Hello, can't say this is an issue, but with current problems with sparkle cards fan any chance to mod vbios to amend their fan curve?

**Comment by Solaris17** [comment]
Not something I dabble into on this repo. I personally only utilize the tool in the arc control panel, with the exception of the certificate locations, I haven't; and I'm not sure anyone has, mapped the vbios areas. I would go out on a limb though, and guess that this would need to be done from a raw BIOS dump, as the vbios is normally processed and the blobs provided by the drivers and in the matrix I maintain are not the same structure as a rom dump from the chip.
